# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  GROQ_API_KEY: ${{ secrets.KEY }}
  GROQ_MODEL: llama-3.3-70b-versatile
  GROQ_MODEL_TEMP: 0
  TEST_ENTRY_URL: https://github.com/guidepup/guidepup
  TEST_CASE_JSON_PATH: example-goals.json

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Set Up Environment For Screen Reader Automation
      uses: guidepup/setup-action
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: sh setup.sh
    - run: npx @guidepup/setup
    - run: npx playwright test
